directories:
  output: build
  buildResources: build
productName: Btap
appId: com.example.btap
releaseInfo:
  releaseNotes: |-
    1. 优化部分UI显示
    2. 增加设置页面的关于内容
    3. 去除部分消息提示
    4. 导航条增加用户授权信息的展示
    5. 增加用户退出登陆
publish:
  provider: generic
  url: 'https://qwermikk.github.io/bt-release/'
files:
  - filter:
      - dist/electron/**/*
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
  target:
    - target: nsis
linux:
  icon: build/icons
nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  installerIcon: build/icons/icon.ico
  uninstallerIcon: build/icons/icon.ico
  installerHeaderIcon: build/icons/icon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: BtapRelease
electronVersion: 3.1.13
